include:
  # - board: nice_nano
  #   shield: charybdis_dongle dongle_display
  - board: nice_nano
    shield: charybdis_left
  - board: nice_nano
    shield: charybdis_right
  - board: nice_nano
    shield: settings_reset
  - board: xiao_ble
    shield: forager_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: forager_right rgbled_adapter
  - board: xiao_ble
    shield: visorbearer
    snippet: studio-rpc-usb-uart
  # Temporarily disabled due to Zephyr 4.1 Kconfig incompatibility in prospector-zmk-module
  # - board: xiao_ble
  #   shield: charybdis_dongle prospector_adapter
  #   snippet: studio-rpc-usb-uart
  # - board: xiao_ble
  #   shield: bykeeb_left
  # - board: xiao_ble
  #   shield: bykeeb_right
