include:
  - board: nice_nano_v2
    shield: charybdis_dongle dongle_display
  - board: nice_nano_v2
    shield: charybdis_left
  - board: nice_nano_v2
    shield: charybdis_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: forager_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: forager_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: charybdis_dongle prospector_adapter
  #   snippet: studio-rpc-usb-uart
  # - board: seeeduino_xiao_ble
  #   shield: settings_reset
  # - board: seeeduino_xiao_ble
  #   shield: bykeeb_left
  # - board: seeeduino_xiao_ble
  #   shield: bykeeb_right
