CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610_ALT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=n
CONFIG_ZMK_EXT_POWER=y
#CONFIG_PMW3610_ALT_SWAP_XY=y
#CONFIG_PMW3610_ALT_INVERT_X=y
#CONFIG_PMW3610_ALT_INVERT_Y=y
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=8

#CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
#CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
#CONFIG_BT_BUF_ACL_TX_COUNT=32
#CONFIG_BT_L2CAP_TX_BUF_COUNT=32

#CONFIG_SPI_LOG_LEVEL_DBG=y

#define ZMK_POINTING_DEFAULT_MOVE_VAL 1500 
#define ZMK_POINTING_DEFAULT_SCRL_VAL 20
CONFIG_PMW3610_ALT_RUN_DOWNSHIFT_TIME_MS=3264
#CONFIG_PMW3610_ALT_REST2_SAMPLE_TIME_MS=200
CONFIG_PMW3610_ALT_REST3_SAMPLE_TIME_MS=300
#CONFIG_PMW3610_ALT_RUN_DOWNSHIFT_TIME_MS=500
#CONFIG_PMW3610_ALT_REST1_DOWNSHIFT_TIME_MS=3000
#CONFIG_PMW3610_ALT_REST2_DOWNSHIFT_TIME_MS=30000

CONFIG_ZMK_SLEEP=n
#CONFIG_ZMK_BLE_MOUSE_REPORT_QUEUE_SIZE=2

# disable BLE on peripheral
CONFIG_ZMK_BLE=n

# disable default split transport
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED=n

# enable split esb transport
CONFIG_ZMK_SPLIT_ESB=y

# left peripheral is ID 0 (right is 1)
CONFIG_ZMK_SPLIT_ESB_PERIPHERAL_ID=0

CONFIG_ZMK_SPLIT_ESB_PROTO_TX_ACK=y
CONFIG_ZMK_SPLIT_ESB_PROTO_TX_RETRANSMIT_DELAY=600
CONFIG_ZMK_SPLIT_ESB_PROTO_TX_RETRANSMIT_COUNT=3

# set 1 since CONFIG_ZMK_BLE is disabled on this peripheral
CONFIG_MPSL_TIMESLOT_SESSION_COUNT=1

CONFIG_ZMK_SPLIT_ESB_PROTO_MSGQ_ITEMS=16
CONFIG_ZMK_SPLIT_ESB_EVENT_BUFFER_ITEMS=16
CONFIG_ZMK_SPLIT_ESB_CMD_BUFFER_ITEMS=4

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_ESB_MAX_PAYLOAD_LENGTH=48
CONFIG_ESB_TX_FIFO_SIZE=1

CONFIG_ZMK_BATTERY_REPORTING=y